# Hibernate settings
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Optional: show SQL parameters in logs (useful for debugging)
quarkus.hibernate-orm.log.bind-parameters=true

quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=1024 # Limits the size of logged request/response bodies
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS

# Form-based authentication
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=
quarkus.http.auth.form.error-page=
quarkus.http.auth.form.landing-page=
quarkus.http.auth.form.http-only-cookie=true
#quarkus.http.auth.permission.authenticated.paths=/*
#quarkus.http.auth.permission.authenticated.policy=authenticated

